### ISSUE TITLE
Adding more Properties and expand Example

### ISSUE THREAD

**Issue by juergschweigi** [rhyous/WpfSharp.Controls#1]
Hallo Jerat,
thank you for this Control and spending time for my case sensitive Property, so i have spend a Little time to advance your Control and your eample-solution :)

I have added more Properties and design your example-window a Little bit more usefull :-)
- Checkbox for Change the Case sensitive Search with a new converter (binding to RegexOptions)
- Listbox for select the Background-Color (binding to HighlightBackground)
- Listbox for select the Foreground-Color (binding to HighlightForeground)
- Listbox for select the FontWeight with new Dependency Property

I will upload file here. 
Then you can decide, whether you want to use these changes in your control.

But...
there are Problems with firering the Events when changing the Properties for the Highlighting Text:
for example when i Change the Background-Color in the listbox, the selected Color is only changed when the "Search Words" are changed!!!

Perhaps you an idea, to solve this Problem so as the Hightlighting Text changes when Property is changed.

Greetings Jürgen
[WpfSharp.Controls_ext.zip](https://github.com/rhyous/WpfSharp.Controls/files/500152/WpfSharp.Controls_ext.zip)

**Comment by rhyous** [comment]
Check out the latest commit. 
I implemented binding so the highlight Run object is bound to the dependency properties.
I cleaned up the events.
I cleaned up the regex code and simplified it.
